### PR TITLE
Fixes bug in `inputNull` in SqoopExportSyntax.

### LINKED ISSUE #62: Input Null String Not recognizing  hive null string format in Parlour Export
While doing export using parlour the hive null string (\N) is not getting replaced as NULL even though input null string is specified as "\\\\N".

### PR DESCRIPTION
**Pull request by stephanh**
This closes #62.

`inputNull` was calling both `inputNullNonString` and `inputNullString`. Unfortunately, it wasn't chaining the calls together causing the result of `inputNullString` to be dropped. This bug was probably introduced when chaning from mutable to immutable.

### CODE REVIEW

File: src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala [hunk 1]
```diff
@@ -248,19 +248,19 @@ trait ParlourExportOptions[+Self <: ParlourExportOptions[_]] extends ParlourOpti
   def getBatch() = Option(toSqoopOptions.isBatchMode)
 
   /** The string to be interpreted as null for input string columns */
-  def inputNullString(token: String) = update(_.setInNullStringValue(token))
+  def inputNullString(token: String): Self = update(_.setInNullStringValue(token))
```
Comment (vineethvarghese) [inline src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala]: Was this just for clarity?

Comment (stephanh) [inline src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala]: Yes, an artifact from my debugging. Do you think I should remove it?

File: src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala [hunk 2]
```diff
@@ -248,19 +248,19 @@ trait ParlourExportOptions[+Self <: ParlourExportOptions[_]] extends ParlourOpti
...
-  def inputNullNonString(token: String) = update(_.setInNullNonStringValue(token))
+  def inputNullNonString(token: String): Self = update(_.setInNullNonStringValue(token))
   addOptional("input-null-non-string", (v: String) => so => so.setInNullNonStringValue(v))
   def getInputNullNonString = Option(toSqoopOptions.getInNullNonStringValue)
 
   /** The string to be interpreted as null for input string and input non-string columns */
-  def inputNull(token: String) = {
-    inputNullString(token)
-    inputNullNonString(token)
+  def inputNull(token: String): Self = update { conf =>
```
Comment (rowandavies) [inline src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala]: Just to sure I understand: so the purpose of `update` here is to achieve the type Self?

File: src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala (hunk 1 above)
Comment (vineethvarghese) [inline src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala]: In that case I would prefer we remove it. Some methods with a return type and some without doesn't look nice.

File: src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala (hunk 2 above)
Comment (stephanh) [inline src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala]: The different SqoopSyntax classes store a list of modifications to be made to the Sqoop config. `update` creates a new instance with the right type and the new modifications added to the list of modifications.

File: src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala (hunk 1 above)
Comment (stephanh) [inline src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala]: Done.

File: src/test/scala/au/com/cba/omnia/parlour/ExportSqoopSpec.scala [hunk 3]
```diff
@@ -163,6 +164,19 @@ class ExportSqoopSpec  extends ThermometerSpec with ExportDb { def is = s2"""
...
+
+    def nullExecution =
+      withEnvironment(path(resourceUrl.toString)) {
+        val nullDataOut = Seq((3, Option.empty[String], "002", "F", "M", 225))
+        val expected   = newData.init ++ oldData ++ nullDataOut
+
+        val table = tableSetup(oldData)
+        val dsl = createDsl(table).inputNull("Bart")
+
+        val execution = SqoopExecution.sqoopExport(dsl)
```
Comment (vineethvarghese) [inline src/test/scala/au/com/cba/omnia/parlour/ExportSqoopSpec.scala]: Minor point but you don't need this val.

Comment (stephanh) [inline src/test/scala/au/com/cba/omnia/parlour/ExportSqoopSpec.scala]: You are right. All the other tests in that file follow that pattern though so I will just leave it for the moment. We should probably refactor parlour to remove the flow support and just stick to execution.

**Comment by stephanh** [comment]
@vineethvarghese happy for me to merge?

**Comment by vineethvarghese** [comment]
:+1:

File: src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala (hunk 2 above)
Comment (rowandavies) [inline src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala]: Okay - certainly the code is correct.  (But, I'd still like to understand why chaining the two previous methods that use `update` doesn't achieve the type Self.)

**Comment by rowandavies** [comment]
:+1:

File: src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala (hunk 2 above)
Comment (stephanh) [inline src/main/scala/au/com/cba/omnia/parlour/SqoopSyntax.scala]: Me too :smile:.I have some vague theories around it but nothing I can verify.
